name: Trigger Android Sync

on:
  push:
    branches:
      - main

jobs:
  notify-android-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ANDROID_REPO_PAT }}
          repository: chidreams/Artemis-Patch-Collection-Android
          event_type: sync_android_patches
